# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemmessage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessage',
            name='status',
            field=models.IntegerField(choices=[(1, '已读'), (0, '未读')], default=0, verbose_name='状态'),
        ),
    ]
